urls.py
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from . import views


app_name = 'blog'

urlpatterns = [
	path('', views.home, name='home'),
	path('home/<int:page>', views.home, name='home'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),
	path('signup/', views.signup, name='signup'),
	path('confirm/<path:encrypted>', views.confirm, name='confirm'),
	path('post/', views.post, name='post'),
	path('article/<int:article_id>', views.article, name='article'),
	path('profile/<int:user_id>', views.profile, name='profile'),
	path('edit/', views.edit, name='edit'),
	path('changepassword/', views.changepassword, name='changepassword'),
	path('notification/', views.notification, name='notification'),
	path('search/', views.search, name='search'),
	path('topost/', TemplateView.as_view(template_name='post.html'), name='topost'),
	path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
	path('contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
	path('like/', views.like, name='like'),
	path('follow/', views.follow, name='follow'),
	path('comment/', views.comment, name='comment'),
	path('reply/', views.reply, name='reply'),
]

templates/about.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block content %}
<div class="container col-md-8">
	<h2>About</h2>
	<p>An international student studying Information Technology in UNSW(The University of New South Wales), Sydney, Australia. Good at web application developing based on Django, Flask, SpingMVC and Bootstrap. Having the ability of coding with C/C++, Perl/Shell and SQL as well.</p>
	<p>Spend most of the spare time on movies, music and football.</p>
	<p>Faith is Manchester United.</p>
	<p>Love is Coldplay.</p>
	<p>Can't live without YouTube. Can't code without Stack Overflow.</p>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>MT</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/ionicons.css' %}">
</head>
<body>
	<button onclick="topFunction()" id="toTop"><i class="ion-android-arrow-up icon-style"></i></button>
	<div id="header" class="shadow">
		<nav class="navbar navbar-expand-lg navbar-light bg-white navi-bottom">
			<a class="navbar-brand text-primary" href="{% url 'blog:home' 1 %}"><b>MT</b></a>

			<!-- <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
			<div class="col-md-11">
				<div class="row" id="navbarSupportedContent">
					<form class="form-inline my-2 my-lg-0 mr-auto navi-search text-left" action="{% url 'blog:search'%}" method="post">
						{% csrf_token %}
						<input type="hidden" name="page" value=1>
						<input class="form-control mr-sm-2" name="keyword" type="search" placeholder="Search for ..." aria-label="Search" required>
						<select name="selection" class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inlineFormCustomSelectPref">
							<option value="user" selected>User</option>
							<option value="article">Article</option>
						</select>
						<button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
					</form>
					{% if request.session.account %}
					<ul class="my-navbar-nav text-right">
						<li class="nav-item">
							<a class="navbar-brand text-success" href="{% url 'blog:profile' request.session.account.id %}">Hi, {{ request.session.account.username }}</a>
						</li>
						<li class="nav-item">
							<a class="navi-btn my-btn-color" href="{% url 'blog:notification' %}"><i class="ion-ios-bell"></i></a>
						</li>
						<li class="nav-item">
							<a class="navi-btn my-btn-color" href="{% url 'blog:topost' %}"><i class="ion-ios-compose"></i></a>
						</li>
						<li class="nav-item">
							<a class="navi-btn" href="{% url 'blog:logout' %}"><i class="ion-log-out text-danger"></i></a>
						</li>
					{% else %}
					<ul class="my-navbar-nav text-right">
						<li class="nav-item">
							<a class="btn btn-outline-success mr-2" href="{% url 'blog:login' %}">Log in</a>
						</li>
						<li class="nav-item">
							<a class="btn btn-outline-success" href="{% url 'blog:signup' %}">Sign up</a>
						</li>
					</ul>
					{% endif %}
				</div>
			</div>
		</nav>
	</div>
	<div id="content">
	{% block content %}
	{% endblock %}
	</div>

	<footer id="footer">
		<div>
			<small>
				<span>Coded by <span class="text-primary">Someone</span> who dreams of <span class="text-success">Changing</span> the <span class="text-warning">World</span></span>
			</small>
		</div>
		<div>
			<small>Copyright 2018 | <a class="text-white" href="{% url 'blog:about' %}">About me</a> | <a class="text-white" href="{% url 'blog:contact' %}">Contact</a></small>
		</div>
	</footer>

<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="reply-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="myModalLabel">Please Login!</h5>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<a class="btn btn-primary" href="{% url 'blog:login' %}">Go to Login</a>
			</div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/blank.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block content %}
<div class="container col-md-8 text-center">
	{{ message }}
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block content %}
<div class="container col-md-8">
	{% for article in articles %}
	<div class="row py-2 border">
		<div class="col-md-1">
			<div class="square">
				<a href="{% url 'blog:profile' article.author.id %}"><img class="sqaure-image rounded" src="{{ article.author.image.url }}"/></a>
			</div>
		</div>
		<div class="col-md-9">
			<a href="{% url 'blog:article' article.id %}">
			<div class="font-weight-bold">
				<h5>{{ article.title }}</h5>
			</div>
			</a>
			<div class="row" id="article" article-id={{ article.id }}>
					<div class="col-md-2"><a class="my-btn-color" href="{% url 'blog:article' article.id %}"><i class="ion-chatbox-working"></i></a> <span> {{ article.comment_nb }} </span></div>
					{% if request.session.account  %}
						{% if article.liked == 0 %}
						<div class="col-md-2"><span class="my-btn-color like-btn"><i class="ion-heart"></i></span> <span class="like-nb">{{ article.like_nb }}</span></div>
						{% else %}
						<div class="col-md-2"><span class="dislike like-btn"><i class="ion-heart"></i></span> <span class="like-nb">{{ article.like_nb }}</span></div>
						{% endif %}
					{% else %}
						<div class="col-md-2"><span class="my-btn-color login-btn" data-toggle="modal" data-target="#login-modal"><i class="ion-heart"></i></span> <span class="like-nb">{{ article.like_nb }}</span></div>
					{% endif %}
			</div>
		</div>
		<div class="col-md-2">
			<div class="font-weight-bold text-right">
				{{ article.modified_time|date:"d M" }}
			</div>
			<div class="text-right">
				<small>{{ article.modified_time|date:"Y" }}</small>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

<div class="paginator mt-4">
	{% if articles.has_previous %}<div class="side page-item"><a class="page-link" href="{% url 'blog:home' articles.previous_page_number %}"><</a></div>{% else %}<div class="side"></div>{% endif %}<div class="middle page-middle">Page {{ articles.number }} of {{ articles.paginator.num_pages }}</div>{% if articles.has_next %}<div class="side page-item"><a class="page-link" href="{% url 'blog:home' articles.next_page_number %}">></a></div>{% else %}<div class="side"></div>{% endif %}
</div>
{% endblock %}

templates/notification.html
{% extends 'base.html' %}
{% load staticfiles%}
{% load myfilter %}
{% block content %}
<div class="container col-md-8">
	<ul class="nav nav-tabs" id="myTab" role="tablist">
		<li class="nav-item">
			<a class="nav-link active my-btn-color" id="comments-tab" data-toggle="tab" href="#comments" role="tab" aria-controls="comments" aria-selected="true">Comments</a>
		</li>
		<li class="nav-item">
			<a class="nav-link my-btn-color" id="replies-tab" data-toggle="tab" href="#replies" role="tab" aria-controls="replies" aria-selected="true">Replies</a>
		</li>
		<li class="nav-item">
			<a class="nav-link my-btn-color" id="likes-tab" data-toggle="tab" href="#likes" role="tab" aria-controls="likes" aria-selected="false">Likes</a>
		</li>
		<li class="nav-item">
			<a class="nav-link my-btn-color" id="followers-tab" data-toggle="tab" href="#followers" role="tab" aria-controls="followers" aria-selected="false">Followers</a>
		</li>
	</ul>
	<div class="tab-content" id="myTabContent">
		<div class="tab-pane fade show active" id="comments" role="tabpanel" aria-labelledby="comments-tab">
			<div class="container col-md-12">
				{% if comments %}
				{% for comment in comments %}
				<div class="row py-2 border border-top-0 border-right-0 border-left-0">
					<div class="col-md-12">
						<a href="{% url 'blog:article' comment.article_id %}">
							<div class="font-weight-bold">
								<h5>{{ comment.title }}</h5>
							</div>
						</a>
						<div class="row">
							<div class="col-md-1 mt-2">
								<div class="square">
									<a href="{% url 'blog:profile' comment.user_id %}"><img class="rounded sqaure-image" src="{{ comment.user.image.url }}"/></a>
								</div>
							</div>
							<div class="col-md-11">
								<div><a href="{% url 'blog:profile' comment.user_id %}">{{ comment.user.username }}</a><span class="bullet text-muted">•</span><small class="text-muted">{{ comment.time_stamp|timesince|upto:',' }} ago</small></div>
								<div>{{ comment.content }}</div>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				{% else %}
				<div class="py-2 text-center">
					<h4>Oops! Nothing Here!</h4>
				</div>
				{% endif %}
			</div>
		</div>
		<div class="tab-pane fade" id="replies" role="tabpanel" aria-labelledby="replies-tab">
			<div class="container col-md-12">
				{% if replies %}
				{% for reply in replies %}
				<div class="row py-2 border border-top-0 border-right-0 border-left-0">
					<div class="col-md-12">
						<a href="#">
							<div class="font-weight-bold">
								<h5>{{ reply.comment }}</h5>
							</div>
						</a>
						<div class="row">
							<div class="col-md-1 mt-2">
								<div class="square">
									<a href="{% url 'blog:profile' reply.user_id %}"><img class="rounded sqaure-image" src="{{ reply.user.image.url }}"/></a>
								</div>
							</div>
							<div class="col-md-11">
								<div><a href="{% url 'blog:profile' reply.user_id %}">{{ reply.user.username }}</a><span class="bullet text-muted">•</span><small class="text-muted">{{ reply.time_stamp|timesince|upto:',' }} ago</small></div>
								<div>{{ reply.content }}</div>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				{% else %}
				<div class="py-2 text-center">
					<h4>No Reply</h4>
				</div>
				{% endif %}
			</div>
		</div>
		<div class="tab-pane fade" id="likes" role="tabpanel" aria-labelledby="likes-tab">
			<div class="container col-md-12">
				{% if likes %}
				{% for like in likes %}
				<div class="row py-2 border border-top-0 border-right-0 border-left-0">
					<div class="col-md-1">
						<div class="square">
							<a href="{% url 'blog:profile' like.user.id %}"><img class="sqaure-image rounded" src="{{ like.user.image.url }}"/></a>
						</div>
					</div>
					<div class="col-md-11 pt-1 pl-0">
						<a href="{% url 'blog:profile' like.user.id %}">{{ like.user.username }}</a> liked your article <a href="{% url 'blog:article' like.article_id %}">{{ like.title }}</a><span class="bullet text-muted">•</span><small class="text-muted">{{ like.time_stamp|timesince|upto:',' }} ago</small>
					</div>
				</div>
				{% endfor %}
				{% else %}
				<div class="py-2 text-center">
					<h4>Oops! Nothing Here!</h4>
				</div>
				{% endif %}
			</div>
		</div>
		<div class="tab-pane fade" id="followers" role="tabpanel" aria-labelledby="followers-tab">
			<div class="container col-md-12">
				{% if friends %}
				{% for friend in friends %}
				<div class="row py-2 border border-top-0 border-right-0 border-left-0">
					<div class="col-md-1">
						<div class="square">
							<a href="{% url 'blog:profile' friend.user.id %}"><img class="sqaure-image rounded" src="{{ friend.user.image.url }}"/></a>
						</div>
					</div>
					<div class="col-md-9 pt-1 pl-0">
						<a href="{% url 'blog:profile' friend.user.id %}">{{ friend.user.username }}</a> started following you <span class="bullet text-muted">•</span><small class="text-muted">{{ friend.time_stamp|timesince|upto:',' }} ago</small>
					</div>
					<div class="col-md-2" id="user" user-id={{ friend.user.id }}>
						{% if friend.is_friend %}
						<button class="btn btn-outline-primary btn-sm follow-btn">Following</button>
						{% else %}
						<button class="btn btn-primary btn-sm follow-btn">Follow</button>
						{% endif %}
					</div>
				</div>
				{% endfor %}
				{% else %}
				<div class="py-2 text-center">
					<h4>Oops! Nothing Here!</h4>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block content %}
<form action="{% url 'blog:post' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="container col-md-8">
		<div class="row">
			<div class="col-md-2 pt-1">Titile</div>
			<div class="col-md-10"><input class="form-titile" type="text" name="title" required></div>
		</div>
		<div class="row my-5">
			<div class="col-md-2 pt-1">Content</div>
			<div class="col-md-10">
				<textarea name="content" required>Say something ... </textarea>
			</div>
		</div>
		<div class="row">
			<div class="col-md-10"></div>
			<div class="col-md-2">
				<input class="btn btn-primary" type="submit" value="Submit">
			</div>
		</div>
	</div>
</form>

<script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script language="javascript" type="text/javascript">
	tinymce.init({
		selector: 'textarea',
		menubar : false,
		mode :"exact",
		autoresize_min_height:300,
		nowrap : false ,
		relative_urls : false,
		remove_script_host : true,
		default_link_target: "_blank",
		plugins: [
			"advlist autolink link lists charmap print preview hr anchor pagebreak spellchecker",
			"searchreplace  visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
			"save  contextmenu directionality emoticons template  textcolor",
			"paste autoresize media codesample",
		],
		codesample_languages: [
			{text: 'HTML/XML', value: 'markup'},
			{text: 'JavaScript', value: 'javascript'},
			{text: 'CSS', value: 'css'},
			{text: 'PHP', value: 'php'},
			{text: 'Python', value: 'python'},
			{text: 'Java', value: 'java'},
			{text: 'C', value: 'c'},
			{text: 'C#', value: 'csharp'},
			{text: 'C++', value: 'cpp'},
			{text: 'SQL', value: 'sql'},
			{text: 'Bash', value: 'bash'},
			{text: 'Git', value: 'git'},
			{text: 'Perl', value: 'perl'},
		],
		toolbar: "insertfile undo redo |  bold italic strikethrough | alignleft aligncenter alignright | link |  code  preview  |  codesample", 
	});
</script>
{% endblock %}`

templates/profile.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block content %}
<div class="container col-md-8">
	<div class="row py-2">
		<div class="col-md-3">
			<div class="square">
				<img class="sqaure-image rounded" src="{{ user.image.url }}">
			</div>
		</div>
		<div class="col-md-9">
			<div class="row py-2">
				<div class="col-md-6">
					<h3>{{ user.username }}</h3>
				</div>
				{% if request.session.account %}
					{% if user.id == request.session.account.id %}
					<div class="col-md-3">
						<button class="btn btn-primary btn-sm" onclick="location.href='{% url 'blog:changepassword' %}';">Change Password</button>
					</div>
					<div class="col-md-3">
						<button class="btn btn-primary btn-sm" onclick="location.href='{% url 'blog:edit' %}';">Edit Profile</button>
					</div>
					{% else %}
					<div class="col-md-6" id="user" user-id={{ user.id }}>
						{% if is_followed %}
						<button class="btn btn-outline-primary btn-sm follow-btn">Following</button>
						{% else %}
						<button class="btn btn-primary btn-sm follow-btn">Follow</button>
						{% endif %}
					</div>
					{% endif %}
				{% else %}
					<div class="col-md-6">
						<button class="btn btn-primary btn-sm login-btn" data-toggle="modal" data-target="#login-modal">Follow</button>
					</div>
				{% endif %}
			</div>
			<div class="row py-2">
				<div class="col-md-12">
					{{ user.profile }}
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container col-md-8 mt-4">
	<ul class="nav nav-tabs" id="myTab" role="tablist">
		<li class="nav-item">
			<a class="nav-link active my-btn-color" id="articles-tab" data-toggle="tab" href="#articles" role="tab" aria-controls="articles" aria-selected="true">Articles</a>
		</li>
		<li class="nav-item">
			<a class="nav-link my-btn-color" id="followers-tab" data-toggle="tab" href="#followers" role="tab" aria-controls="followers" aria-selected="false">Followers</a>
		</li>
		<li class="nav-item">
			<a class="nav-link my-btn-color" id="following-tab" data-toggle="tab" href="#following" role="tab" aria-controls="following" aria-selected="false">Following</a>
		</li>
	</ul>
	<div class="tab-content" id="myTabContent">
		<div class="tab-pane fade show active" id="articles" role="tabpanel" aria-labelledby="articles-tab">
			<div class="container col-md-12">
				{% if articles %}
				{% for article in articles %}
				<div class="row py-2 border border-top-0 border-right-0 border-left-0">
					<div class="col-md-10">
						<a href="{% url 'blog:article' article.id %}">
							<div class="font-weight-bold">
								<h5>{{ article.title }}</h5>
							</div>
						</a>
						<div class="row" id="article" article-id={{ article.id }}>
							<div class="col-md-2"><a class="my-btn-color" href="{% url 'blog:article' article.id %}"><i class="ion-chatbox-working"></i></a> <span> {{ article.comment_nb }} </span></div>
							{% if request.session.account  %}
								{% if article.liked == 0 %}
								<div class="col-md-2"><span class="my-btn-color like-btn"><i class="ion-heart"></i></span> <span class="like-nb">{{ article.like_nb }}</span></div>
								{% else %}
								<div class="col-md-2"><span class="dislike like-btn"><i class="ion-heart"></i></span> <span class="like-nb">{{ article.like_nb }}</span></div>
								{% endif %}
							{% else %}
								<div class="col-md-2"><span class="my-btn-color login-btn" data-toggle="modal" data-target="#login-modal"><i class="ion-heart"></i></span> <span class="like-nb">{{ article.like_nb }}</span></div>
							{% endif %}
						</div>
					</div>
					<div class="col-md-2">
						<div class="font-weight-bold text-right">
							{{ article.modified_time|date:"d M" }}
						</div>
						<div class="text-right">
							<small>{{ article.modified_time|date:"Y" }}</small>
						</div>
					</div>
				</div>
				{% endfor %}
				{% else %}
				<div class="py-2 text-center">
					<h4>Oops! Nothing Here!</h4>
				</div>
				{% endif %}
			</div>
		</div>
		<div class="tab-pane fade" id="followers" role="tabpanel" aria-labelledby="followers-tab">
			<div class="container col-md-12">
				{% if followers %}
				{% for follower in followers %}
				<div class="row py-2 border border-top-0 border-right-0 border-left-0">
					<div class="col-md-1">
						<div class="square">
							<a href="{% url 'blog:profile' follower.user.id %}"><img class="sqaure-image rounded" src="{{ follower.user.image.url }}" /></a>
						</div>
					</div>
					<div class="col-md-9 pt-1 pl-0">
						<a href="{% url 'blog:profile' follower.user.id %}">{{ follower.user.username }}</a>
					</div>
					{% if request.session.account %}
						{% if follower.user.id != request.session.account.id %}
						<div class="col-md-2" id="user" user-id={{ follower.user.id }}>
							{% if follower.is_followed %}
							<button class="btn btn-outline-primary btn-sm follow-btn">Following</button>
							{% else %}
							<button class="btn btn-primary btn-sm follow-btn">Follow</button>
							{% endif %}
						</div>
						{% endif %}
					{% else %}
						<div class="col-md-2">
							<button class="btn btn-primary btn-sm login-btn" data-toggle="modal" data-target="#login-modal">Follow</button>
						</div>
					{% endif %}
				</div>
				{% endfor %}
				{% else %}
				<div class="py-2 text-center">
					<h4>Oops! Nothing Here!</h4>
				</div>
				{% endif %}
			</div>
		</div>
		<div class="tab-pane fade" id="following" role="tabpanel" aria-labelledby="following-tab">
			<div class="container col-md-12">
				{% if followings %}
				{% for following in followings %}
				<div class="row py-2 border border-top-0 border-right-0 border-left-0">
					<div class="col-md-1">
						<div class="square">
							<a href="{% url 'blog:profile' following.user.id %}"><img class="sqaure-image rounded" src="{{ following.user.image.url }}" /></a>
						</div>
					</div>
					<div class="col-md-9 pt-1 pl-0">
						<a href="{% url 'blog:profile' following.user.id %}">{{ following.user.username }}</a>
					</div>
					{% if request.session.account %}
						{% if following.user.id != request.session.account.id %}
						<div class="col-md-2" id="user" user-id={{ following.user.id }}>
							{% if following.is_followed %}
							<button class="btn btn-outline-primary btn-sm follow-btn">Following</button>
							{% else %}
							<button class="btn btn-primary btn-sm follow-btn">Follow</button>
							{% endif %}
						</div>
						{% endif %}
					{% else %}
						<div class="col-md-2">
							<button class="btn btn-primary btn-sm login-btn" data-toggle="modal" data-target="#login-modal">Follow</button>
						</div>
					{% endif %}
				</div>
				{% endfor %}
				{% else %}
				<div class="py-2 text-center">
					<h4>Oops! Nothing Here!</h4>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/result.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block content %}
<div class="container col-md-8 text-center mb-5">
	<h1>Search Result</h1>
	<h><strong>{{ lenOfresults }}</strong> {% if lenOfresults > 1 %}results{% else %}result{% endif %} about "<strong>{{ keyword }}</strong>" in <strong>{{ selection }}</strong>.</h>
</div>
<div class="container col-md-8">
	{% if selection == 'article' and results %}
		{% for article in results %}
			<div class="row">
				<div class="col-md-10">
					<h2><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a></h2>
				</div>

				<div class="col-md-2">
					<div class="font-weight-bold text-right">
						{{ article.modified_time|date:"d M" }}
					</div>
					<div class="text-right">
						<small>{{ article.modified_time|date:"Y" }}</small>
					</div>
				</div>
			</div>
			<div class="row border border-top-0 border-right-0 border-left-0 pb-3 mb-4">
				<div class="col-md-12">
					{% autoescape off %}
					{{ article.content | truncatechars:255 }}
					{% endautoescape %}
				</div>
			</div>
		{% endfor %}
	{% elif selection == 'user' and results %}
		{% for user in results %}
			<div class="row py-2 border border-top-0 border-right-0 border-left-0">
				<div class="col-md-1">
					<div class="square">
						<a href="{% url 'blog:profile' user.id %}"><img class="sqaure-image rounded" src="{{ user.image.url }}" /></a>
					</div>
				</div>
				<div class="col-md-9 pl-0">
					<h3><a href="{% url 'blog:profile' user.id %}">{{ user.username }}</a></h3>
				</div>
				{% if request.session.account  %}
					{% if user.id != request.session.account.id %}
					<div class="col-md-2" id="user" user-id={{ user.id }}>
						{% if is_followed %}
						<button class="btn btn-outline-primary btn-sm follow-btn">Following</button>
						{% else %}
						<button class="btn btn-primary btn-sm follow-btn">Follow</button>
						{% endif %}
					</div>
					{% endif %}
				{% else %}
				<div class="col-md-2">
					<button class="btn btn-primary btn-sm mt-1 login-btn" data-toggle="modal" data-target="#login-modal">Follow</button>
				</div>
				{% endif %}
			</div>
		{% endfor %}
	{% endif %}
</div>

{% if results %}
<div class="paginator mt-4">
	{% if results.has_previous %}<div class="side page-item"><form action="{% url 'blog:search' %}" method="POST">{% csrf_token %}<input type="hidden" name="page" value={{ results.previous_page_number }}><input type="hidden" name="keyword" value={{ keyword }}><input type="hidden" name="selection" value={{ selection }}><button class="page-link" type="submit"><</button></form></div>{% else %}<div class="side"></div>{% endif %}<div class="middle page-middle">Page {{ results.number }} of {{ results.paginator.num_pages }}</div>{% if results.has_next %}<div class="side page-item"><form href="{% url 'blog:search' %}" method="POST">{% csrf_token %}<input type="hidden" name="page" value={{ results.next_page_number }}><input type="hidden" name="keyword" value={{ keyword }}><input type="hidden" name="selection" value={{ selection }}><button type="submit" class="page-link">></button></form></div>{% else %}<div class="side"></div>{% endif %}
</div>
{% endif %}
{% endblock %}`

templates/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container col-md-5 px-4 py-2 loginblock shadow">
	<h1 class="text-center text-primary py-2">Join MT Today!</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-group row">
			<label class="col-md-4 col-form-label">Email</label>
			<div class="col-sm-8">
	     		{{ form.email }}
	    	</div>
		</div>
		<div class="form-group row">
			<label class="col-md-4 col-form-label">Username</label>
			<div class="col-sm-8">
	     		{{ form.username }}
	    	</div>
		</div>
		<div class="form-group row">
			<label class="col-md-4 col-form-label">Password</label>
			<div class="col-sm-8">
	     		{{ form.password1 }}
	    	</div>
		</div>
		<div class="form-group row">
			<label class="col-md-4 col-form-label">Confirm Password</label>
			<div class="col-sm-8">
	     		{{ form.password2 }}
	    	</div>
		</div>
		<div class="form-group row">
			<div class="col text-center">
				<button type="submit" class="btn btn-outline-primary btn-lg btn-block">Sign up</button>
			</div>
		</div>
	</form>

	<div class="text-center">Already have an account? <a href="{% url 'blog:login' %}">Log in<a></div>
</div>

<h5 class="text-center text-danger mt-2">{{ error }}</h5>
{% endblock %}